from pathlib import Path
import sys
import time

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

load_dotenv(ROOT / ".env")

from app.models import (  # noqa: E402
    ConversationCreateRequest,
    FeedbackCreateRequest,
    InteractionSaveRequest,
    RecommendationSaveItem,
)
from app.services.qdrant_service import QdrantService  # noqa: E402
from app.services.supabase_service import SupabaseService  # noqa: E402
from app.config import get_settings  # noqa: E402


def main() -> None:
    settings = get_settings()
    supabase = SupabaseService(settings)
    qdrant = QdrantService(settings)

    health = supabase.health()
    print(f"supabase_status={health.status}")
    print(f"missing_tables={health.missing_tables}")

    conversation = supabase.create_conversation(
        ConversationCreateRequest(
            session_id=f"backend-smoke-{int(time.time())}",
            title="Backend smoke test",
            metadata={"source": "backend_smoke"},
        )
    )
    print(f"conversation_id={conversation.conversation_id}")

    context = qdrant.build_context(
        query="regularization and overfitting confusion",
        top_k=1,
    )
    print(f"qdrant_evidence_count={context.evidence_count}")

    evidence = []
    for rank, item in enumerate(context.context, start=1):
        payload = item.payload or {}
        evidence.append(
            {
                "point_id": item.point_id,
                "content_type": item.content_type or payload.get("content_type") or "caption",
                "lecture_id": item.lecture_id or payload.get("lecture_id"),
                "module_id": payload.get("module_id"),
                "score": item.score,
                "retrieval_rank": rank,
                "text": item.text,
                "asset_path": payload.get("asset_path"),
                "timestamp_seconds": payload.get("timestamp_seconds")
                or payload.get("start_seconds"),
                "metadata": {
                    "asset_id": item.asset_id,
                    "course_id": item.course_id,
                },
            }
        )

    saved = supabase.save_interaction(
        InteractionSaveRequest(
            conversation_id=conversation.conversation_id,
            query_text="regularization and overfitting confusion",
            generated_answer="Smoke-test answer generated by backend verification.",
            normalized_topic="regularization",
            detected_intent="smoke_test",
            model_name="backend-smoke",
            model_provider="local-test",
            evidence=evidence,
            recommendations=[
                RecommendationSaveItem(
                    recommendation_type="content_improvement",
                    recommendation_text="Review the cited segment for learner confusion signals.",
                    target_record_id=evidence[0]["point_id"] if evidence else None,
                    priority=1,
                    metadata={"source": "backend_smoke"},
                )
            ],
            metadata={"source": "backend_smoke"},
        )
    )
    print(f"query_id={saved.query_id}")
    print(f"response_id={saved.response_id}")
    print(f"saved_evidence={saved.evidence_count}")
    print(f"saved_recommendations={saved.recommendation_count}")

    feedback = supabase.save_feedback(
        FeedbackCreateRequest(
            response_id=saved.response_id,
            rating=5,
            is_helpful=True,
            approval="approved",
            feedback_text="Smoke test feedback",
        )
    )
    print(f"feedback_id={feedback.feedback_id}")

    dashboard = supabase.dashboard_summary()
    print(f"dashboard_activity={dashboard.activity_summary}")


if __name__ == "__main__":
    main()
