import {
  DashboardData,
  DashboardStats,
  PipelineHealth,
  ProcessingMonitorItem,
} from "@/types";

// 1, 2, 4. DASHBOARD KEY METRICS
export const dashboardStats: DashboardStats = {
  totalJobs: 1482,
  failedJobs: 38,
  pendingReview: 124,
  recommendationsAccepted: 892,
  totalAssets: 3840,
  totalAssetsIndexed: 3512,
  totalRecommendationsCurated: 1145,
};

// 3. PIPELINE HEALTH METRICS
export const pipelineHealthData: PipelineHealth = {
  totalUploadedAssets: 3840,
  indexed: 3512,
  review: 194,
  failed: 78,
};

// 5. PROCESSING MONITOR (Strictly using modalities defined in Register Page: Video, Image, Transcript, Quiz, Discussion Thread)
export const processingMonitorData: ProcessingMonitorItem[] = [
  {
    id: "proc-1",
    assetId: "AST-4012",
    assetName: "Deep Learning Specialization - Week 3 Lecture Video",
    assetType: "Video",
    currentStage: "Segmenting & Audio Extraction",
    progress: 68,
    isSearchable: "No",
    status: "in_progress",
    updatedAt: "2 mins ago",
    owner: "Dr. Andrew Ng",
    size: "420 MB",
  },
  {
    id: "proc-2",
    assetId: "AST-4013",
    assetName: "Transformer Attention Architecture Lecture Transcript",
    assetType: "Transcript",
    currentStage: "Generating Multimodal Vector Embeddings",
    progress: 92,
    isSearchable: "No",
    status: "in_progress",
    updatedAt: "4 mins ago",
    owner: "Curriculum Ops",
    size: "14.2 MB",
  },
  {
    id: "proc-3",
    assetId: "AST-4014",
    assetName: "Backpropagation Mathematical Derivation Walkthrough",
    assetType: "Video",
    currentStage: "Knowledge Graph Indexing",
    progress: 100,
    isSearchable: "Yes",
    status: "completed",
    updatedAt: "12 mins ago",
    owner: "Sarah Jenkins",
    size: "850 MB",
  },
  {
    id: "proc-4",
    assetId: "AST-4015",
    assetName: "Week 2 Discussion Forum High-Frequency Confusion Points",
    assetType: "Discussion Thread",
    currentStage: "Semantic Clustering & Indexing",
    progress: 100,
    isSearchable: "Yes",
    status: "completed",
    updatedAt: "18 mins ago",
    owner: "Automated Telemetry Bot",
    size: "2.4 MB",
  },
  {
    id: "proc-5",
    assetId: "AST-4016",
    assetName: "Neural Network Hyperparameter Tuning Screencast",
    assetType: "Video",
    currentStage: "Whisper Speech Transcription",
    progress: 45,
    isSearchable: "No",
    status: "in_progress",
    updatedAt: "25 mins ago",
    owner: "Alex Chen",
    size: "68 MB",
  },
  {
    id: "proc-6",
    assetId: "AST-4017",
    assetName: "Convolutional Kernels Visual Diagram",
    assetType: "Image",
    currentStage: "OCR & Diagram Feature Extraction",
    progress: 82,
    isSearchable: "No",
    status: "in_progress",
    updatedAt: "32 mins ago",
    owner: "Elena Rostova",
    size: "8.7 MB",
  },
  {
    id: "proc-7",
    assetId: "AST-4018",
    assetName: "Week 4 Gradient Descent Formative Assessment",
    assetType: "Quiz",
    currentStage: "Corrupt Question Schema Parsing",
    progress: 30,
    isSearchable: "No",
    status: "failed",
    updatedAt: "45 mins ago",
    owner: "Evaluation Team",
    size: "1.1 MB",
  },
  {
    id: "proc-8",
    assetId: "AST-4019",
    assetName: "Reinforcement Learning Q-Table Key Equations",
    assetType: "Image",
    currentStage: "Human Review Flagged (OCR Low Confidence)",
    progress: 75,
    isSearchable: "No",
    status: "review",
    updatedAt: "1 hour ago",
    owner: "Marcus Vance",
    size: "5.6 MB",
  },
  {
    id: "proc-9",
    assetId: "AST-4020",
    assetName: "PyTorch Lightning Distributed Training Walkthrough",
    assetType: "Video",
    currentStage: "Vector Search Index Registration",
    progress: 100,
    isSearchable: "Yes",
    status: "completed",
    updatedAt: "2 hours ago",
    owner: "Priya Sharma",
    size: "1.2 GB",
  },
  {
    id: "proc-10",
    assetId: "AST-4021",
    assetName: "Optimization Landscapes & Loss Functions Full Transcript",
    assetType: "Transcript",
    currentStage: "Queued in Ingestion Buffer",
    progress: 0,
    isSearchable: "No",
    status: "queued",
    updatedAt: "Just now",
    owner: "Curriculum Ops",
    size: "18.5 MB",
  },
];

// COMBINED DASHBOARD DATA OBJECT
export const dashboardData: DashboardData = {
  stats: dashboardStats,
  pipelineHealth: pipelineHealthData,
  processingMonitor: processingMonitorData,
};
