"use client";

import { useState } from "react";
import { PageHeader } from "@/components/ui/page-header";
import { SearchInput } from "@/components/ui/search-input";

export default function RecommendationsPage() {
  const [searchQuery, setSearchQuery] = useState("");

  return (
    <div className="space-y-6">
      <PageHeader
        title="Recommendations"
        description="Multimodal content suggestions curated using student telemetry and curriculum alignment."
      ></PageHeader>

      {/* Filter and Search Bar */}
      <div className="w-full bg-card">
        <SearchInput
          placeholder="Search recommendations..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          showClear
          onClear={() => setSearchQuery("")}
          className="h-9 text-sm"
        />
      </div>

      {/* TODO: DISPLAY AND LOAD THE RECOMMENDATION GENERATED BY THE CHAT FROM THE ASK SECTION  */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4"></div>
    </div>
  );
}
